name: 合并广告规则

on:
  # 定时执行（每天UTC时间0点，即北京时间8点）
  schedule:
    - cron: '0 16 * * *'
  # 允许手动触发
  workflow_dispatch:
  
permissions:
  contents: write
  
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 设置Python环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 执行合并脚本
        run: python merge.py

      - name: 提交结果到仓库
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          # 跟踪合并规则、重复规则和URL缩写配置
          git add result/ADaway.txt result/duplicates.txt url_aliases.txt
          if git diff --cached --quiet; then
            echo "规则无变化，无需提交"
          else
            COMMIT_TIME=$(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M:%S')
            git commit -m "自动更新合并规则: $COMMIT_TIME"
            git push
          fi
